# Functions

## Functions

Functions are the most important tool to efficiently code in Python. They are great in case you need to repeat the same or very similar code several times.

### Defining and Calling a Function

A function is defined by the keyword *def* and it returns the object in the *return* statement. Multiple *return* statements are allowed. Here is an example:

In [1]:
def greet():
    print("Hello! Welcome to Python.")

# Call the function
greet()

Hello! Welcome to Python.

### Functions with Parameters

You can pass information into a function using **parameters**:

In [3]:
def greet(name):
    print(f"Hello, {name}! Welcome to Python.")

greet("Alice")
greet("Bob")

Hello, Alice! Welcome to Python.
Hello, Bob! Welcome to Python.

### Functions that Return a Value

A function can also **return** a result using the *return* keyword:

In [5]:
def add(a, b):
    result = a + b
    return result

sum1 = add(3, 5)
sum2 = add(10, 20)

print(sum1)   # 8
print(sum2)   # 30

8
30

In [7]:
def my_funct(x, y, z = 2):
    if z > 1:
        return z * (x + y)
    else:
        return z / (x + y)

The third argument has been given a default value of 2. If we do not specify a third argument, the default is used.

In [13]:
output = my_funct(2, 3, 0.5)
output

0.1

In [11]:
my_funct(2, 3)

10

When a function is called, arguments can be provided as **positional arguments** and **keyword arguments**. 

In the following function call, all arguments were provided as positional arguments. The right value is attached to the right variable name based on position: the first one is x, the second one is y, and the third one is z.

In [47]:
my_funct(2, 3, 0.5)

0.1

In the following function call, all arguments were provided as keyword arguments. Note that the order does not matter.

In [48]:
my_funct(y = 2, x = 3)

10

Even though I do not recommend it, you can use a combination of positional and keyword arguments. There are some restrictions on what you can do, however, as illustrated below. 

* All positional arguments need to preceed all keyword arguments.
* The positional arguments need to be in the right position.

In [ ]:
my_funct(x = 3, y = 2)

In [ ]:
my_funct(3, y = 2)

Here is another example of a function, this time including an *if else* statement:

In [15]:
def nationality(name):
    if name == "John":
        print("I am from Kenya!")
    elif name == "Mary":
        print("I am from the USA!")
    else:
        print(name + ", where are you from?")
nationality("John")
nationality("Mary")

I am from Kenya!
I am from the USA!

In [17]:
nationality("Christina")

Christina, where are you from?

# Reading & Writing Data Files

When working with data, the first step is often to load them into Python. First, the file location is specified, 
then a stream to that location is created.

## Importing text files

Python's basic *open* function is what you need. It is used to open a connection to a file. First assign the filename to a variable as a string.

Important remark: use a **double backslash** in file paths on Windows!

In [19]:
filename = "C:\\Users\\Beryl\\Desktop\\Beryl\\KARU\\Units\\Karatina Uni\\SEM II\\STA 326\\Lecture Notes\\New Lecture notes\\Python Lecture notes\\FLAMES_Python_Part_2_2025\\chol.txt" # use this on Windows

In [67]:
filename

'C:\\Users\\Beryl\\Desktop\\Beryl\\KARU\\Units\\Karatina Uni\\SEM II\\STA 326\\Lecture Notes\\New Lecture notes\\Python Lecture notes\\FLAMES_Python_Part_2_2025\\chol.txt'

Then pass *filename* to the *open* function together with the argument *mode = 'r'*, which makes sure that we can only read the file and not write to it. If you want to open a file to write to it, you should pass the argument *mode='w'*.

In [21]:
file = open(filename, mode = 'r')

Next assign the text from the file to a variable *text* by applying the method *read* to the connection to the file.

In [23]:
text = file.read()
text

'AGE\tHEIGHT\tWEIGHT\tCHOL\tSMOKE\tBLOOD\tMORT\n20\t176\t77\t195\tnonsmo\tb\talive\n53\t167\t56\t250\tsigare\to\tdead\n44\t170\t80\t304\tsigare\ta\tdead\n37\t173\t89\t178\tnonsmo\to\talive\n26\t170\t71\t206\tsigare\to\talive\n41\t165\t62\t284\tsigare\to\talive\n39\t174\t75\t232\tsigare\to\talive'

Always make sure you have closed the connection to the file using the *close* method.

In [25]:
file.close()

## Importing flat files

Flat files are basic text files containing records. We can use *pandas* to import flat files if we want to store the data in a DataFrame.

### Importing flat files with *pandas*

Why do you need to import files with *pandas*? Because the majority of data sets are multidimensional, where columns might be of different types. The data structure most relevant to data manipulation and analysis that *pandas* offers, is the *DataFrame* (analogous to *dataframe* in R). A data frame has observations (rows) and variables (columns), which is exactly what we need to perfom statistical analysis. 

To use *pandas* you first have to import it. If you wish to import a .csv file, you only need to call the function *read_csv* and supply it with the name of the file.

In [27]:
import pandas as pd    # first import pandas
filename = "C:\\Users\\Beryl\\Desktop\\Beryl\\KARU\\Units\\Karatina Uni\\SEM II\\STA 326\\Lecture Notes\\New Lecture notes\\Python Lecture notes\\FLAMES_Python_Part_2_2025\\rainfall.csv"    # pass the path to your file
data = pd.read_csv(filename)    # assign the dataframe to variable data 
data.head()    # check the first five rows of the DataFrame

,Unnamed: 0,station_code,city_name,year,month,day,rainfall,period,quality,lat,long,station_name,avg_rainfall
0,0,9151,Perth,1967,7,5,2.8,1,Y,-31.96,115.79,Subiaco Wastewater Treatment Plant,6.884615
1,1,9151,Perth,1967,7,6,4.8,1,Y,-31.96,115.79,Subiaco Wastewater Treatment Plant,6.884615
2,2,9151,Perth,1967,7,7,5.8,1,Y,-31.96,115.79,Subiaco Wastewater Treatment Plant,6.884615
3,3,9151,Perth,1967,7,10,16.0,1,Y,-31.96,115.79,Subiaco Wastewater Treatment Plant,6.884615
4,4,9151,Perth,1967,7,11,1.0,1,Y,-31.96,115.79,Subiaco Wastewater Treatment Plant,6.884615

In [29]:
type(data)

pandas.core.frame.DataFrame

In [121]:
# help(pd.read_csv)

In [31]:
data = pd.read_csv(filename, index_col = 0) # tells Pandas to use the first column (column number 0) as the row labels (index)
data.tail(6)  # displays the last 15 rows

,station_code,city_name,year,month,day,rainfall,period,quality,lat,long,station_name,avg_rainfall
14772,40913,Brisbane,2020,1,1,0.4,1,N,-27.48,153.04,Brisbane,0.066667
14773,40913,Brisbane,2020,1,2,0.0,1,N,-27.48,153.04,Brisbane,0.066667
14774,40913,Brisbane,2020,1,3,0.0,1,N,-27.48,153.04,Brisbane,0.066667
14775,40913,Brisbane,2020,1,4,0.0,1,N,-27.48,153.04,Brisbane,0.066667
14776,40913,Brisbane,2020,1,5,0.0,1,N,-27.48,153.04,Brisbane,0.066667
14777,40913,Brisbane,2020,1,6,0.0,1,N,-27.48,153.04,Brisbane,0.066667

## Writing files

If we want to export new data, e.g. the *pandas DataFrame* object *data* that we created in the previous section, we can use the following methods.

In [129]:
type(data)

pandas.core.frame.DataFrame

In [33]:
# if you do not specify a path, the file will be saved in the folder of your jupyter notebook
out_csv = 'data.csv'
data.to_csv(out_csv)

out_xlsx = 'data.xlsx'
data.to_excel(out_xlsx)

# here is an example where you specify the whole path
data.to_excel("C:\\Users\\Beryl\\Desktop\\Beryl\\KARU\\Units\\Karatina Uni\\SEM II\\STA 326\\Lecture Notes\\New Lecture notes\\Python Lecture notes\\FLAMES_Python_Part_2_2025\\data1.xlsx")

#  *NumPy*

In general, a Python library is a collection of functions and methods that allows you to perform actions without writing your own code. If you are working with data, some libraries are foundational: *NumPy, pandas, Matplotlib*, ...

*NumPy*, short for Numerical Python, is one of the most important foundational packages for numerical computing in Python. The aim of this chapter is to give an understanding of *NumPy* arrays and array-oriented computation, which will help you use tools with array-oriented semantics, like *pandas*, in a more effective way. 

*NumPy* provides an alternative to the Python list data structure: *NumPy* array. It is similar to a list but it has additional features, such as the ability to perform calculation over entire arrays in an easy and fast way. It is not part of the core Python installation (download from www.python.org), so you have to download it. However, NumPy is part of the "Anaconda distribution" (download from https://anaconda.org).

You can import the *NumPy* package to use it in your Python session; *np* is the standard convention used to import *NumPy*. You can decide to not follow this convention, but we will in this manual.

In [35]:
import numpy as np

## *NumPy* arrays

We will cover only a small portion of *NumPy* features in this chapter. The first important concept we introduce is an array. To create a *NumPy* array, you can use the *array* function and simply specify a regular Python list as input data.

In [37]:
height_array = np.array([1.55, 1.78, 1.65, 1.67, 1.88, 1.71])  # height of people
height_array

array([1.55, 1.78, 1.65, 1.67, 1.88, 1.71])

In [39]:
weight_array = np.array([52.1, 66.3, 65.8, 55.9, 84.5, 67.3])  # weight of people 
weight_array

array([52.1, 66.3, 65.8, 55.9, 84.5, 67.3])

If we want to calculate the Body Mass Index (BMI) of this group of people, we can do it as follows:

In [42]:
bmi = weight_array / height_array ** 2
bmi

array([21.68574402, 20.92538821, 24.16896235, 20.04374485, 23.90787687,
       23.01562874])

The calculations with arrays were performed element-wise.

If you would have tried to do the same calculation with regular lists, you would get an error!

In [ ]:
# bmi calculation with lists 
height = [1.55, 1.78, 1.65, 1.67, 1.88, 1.71]
weight = [52.1, 66.3, 65.8, 55.9, 84.5, 67.3]
weight / height ** 2 # ERROR!

Recall that the + operator for lists concatenates the lists. For arrays, however, it computes the element-wise addition.

In [46]:
height + weight # concatenation

[1.55, 1.78, 1.65, 1.67, 1.88, 1.71, 52.1, 66.3, 65.8, 55.9, 84.5, 67.3]

In [12]:
height_array + weight_array # element-wise addition

array([53.65, 68.08, 67.45, 57.57, 86.38, 69.01])

Besides the fact that NumPy operations tend to act element-wise, there is one other important consideration to keep in mind: *NumPy* assumes that your *NumPy* array only contains values of a single type. If you try to create an array with different types, the resulting *NumPy* array will contain a single type. In the following example, the Boolean and the float are converted to strings:

In [52]:
np.array([7.5, "today", False])

array(['7.5', 'today', 'False'], dtype='<U32')

In general, you can work with *NumPy* arrays in the same as you can with regular Python lists.

In [54]:
# print the array
height_array

array([1.55, 1.78, 1.65, 1.67, 1.88, 1.71])

In [58]:
# access the first element
height_array[4]

1.88

There is specific way to subset a *NumPy* array using an array of Booleans. This does not work for lists.

In [16]:
height_array

array([1.55, 1.78, 1.65, 1.67, 1.88, 1.71])

In [60]:
height_array < 1.7

array([ True, False,  True,  True, False, False])

In [62]:
height_array[height_array <= 1.67]   #Select only the elements whose condition is True

array([1.55, 1.65, 1.67])

In [64]:
height

[1.55, 1.78, 1.65, 1.67, 1.88, 1.71]

In [ ]:
height < 1.7 ##ERROR

## 2D *NumPy* arrays

Take a look at the type of *NumPy* array *height* that we created in the previous section.

In [20]:
type(height_array)

numpy.ndarray

The output indicates it is a type defined in the *NumPy* package, where *ndarray* stands for "n-dimensional array". 

Our array *height_array* is a one-dimesional array, but is it possible to create two, three, ..., or n-dimensional arrays! You can create 2D arrays from a regular Python list of lists.

In [68]:
array_2d = np.array([[1.55, 1.78, 1.65, 1.67, 1.88, 1.71],
                    [52.1, 66.3, 65.8, 55.9, 84.5, 67.3]])
array_2d

array([[ 1.55,  1.78,  1.65,  1.67,  1.88,  1.71],
       [52.1 , 66.3 , 65.8 , 55.9 , 84.5 , 67.3 ]])

In [70]:
array2 = np.array([
    [1.55, 52.1],
    [1.78, 66.3],
    [1.65, 65.8],
    [1.67, 55.9],
    [1.88, 84.5],
    [1.71, 67.3]
])
array2

array([[ 1.55, 52.1 ],
       [ 1.78, 66.3 ],
       [ 1.65, 65.8 ],
       [ 1.67, 55.9 ],
       [ 1.88, 84.5 ],
       [ 1.71, 67.3 ]])

We obtain a data structure where each sublist in the list corresponds to a row in the 2-dimensional array. You can obtain the number of rows and columns using the *shape* attribute.

In [72]:
array_2d.shape

(2, 6)

In [74]:
array2.shape

(6, 2)

In [76]:
array_2d[1] # select the second row

array([52.1, 66.3, 65.8, 55.9, 84.5, 67.3])

In [86]:
array2[:,1]

array([52.1, 66.3, 65.8, 55.9, 84.5, 67.3])

In [88]:
array_2d

array([[ 1.55,  1.78,  1.65,  1.67,  1.88,  1.71],
       [52.1 , 66.3 , 65.8 , 55.9 , 84.5 , 67.3 ]])

array2

In [90]:
print(array_2d[1][3]) # select the fourth element in the second row

55.9

In [92]:
print(array_2d[0, 2]) # select the third element in the first row

1.65

In [94]:
array_2d[:, 1:3] # to select second & third elements of both rows

array([[ 1.78,  1.65],
       [66.3 , 65.8 ]])

## Basic Statistics with *Numpy*

You can generate useful summary statistics about you data with *NumPy*.

In [96]:
Mean=np.mean(height_array) # mean
print(Mean)
Median=np.median(height_array) # median
print(Median)
Variance=np.var(height_array) # variance
print(Variance)
Std=np.std(height_array) # standard deviation 
print(Std)
Min=np.min(height_array) # minimum
print(Min)
Max=np.max(height_array) # maximum
print(Max)
Cor=np.corrcoef(height_array, weight_array) # correlation
print(Cor)

1.706666666666667
1.69
0.010755555555555551
0.10370899457402695
1.55
1.88
[[1.         0.90378738]
 [0.90378738 1.        ]]

We can even compute the mean/median/var/std/min/max of all rows or columns in a 2d array using the axis option.

In [144]:
array_2d

array([[ 1.55,  1.78,  1.65,  1.67,  1.88,  1.71],
       [52.1 , 66.3 , 65.8 , 55.9 , 84.5 , 67.3 ]])

In [98]:
Mean_Wgt_Hgt=np.mean(array_2d) # Computes the overall mean of all values in the entire array (does not make much sense)
print(Mean_Wgt_Hgt)
Mean_Wgt_Hgt_pp=np.mean(array_2d, axis = 0) # mean of weight and height per person- Computes the mean column by column(does not make much sense either)
print(Mean_Wgt_Hgt_pp)
Mean_Hgt_Wgt=np.mean(array_2d, axis = 1) # mean height and mean weight -Computes the mean row by row
print(Mean_Hgt_Wgt)

33.51166666666667
[26.825 34.04  33.725 28.785 43.19  34.505]
[ 1.70666667 65.31666667]

## Exercises: Working with *NumPy*

**Exercise 1**

Use these data about NBA basketball players to practice your *NumPy* skills: start by creating *players_skinny*, a list of lists with the weight (in kilos) and height (in centimeters) of skinny players with the following code (you can omit the name displayed as comments):

In [ ]:
 players_skinny = [[74, 183], # Allen Iverson
                  [68, 183],  # Elliot Perry 
                  [77, 190],  # Fat Lever
                  [78, 185],  # Dennis Schroder
                  [79, 188]]  # Gus Williams

Then:

    - Create a 2D numpy array from players_skinny called NBA_skinny & get the shape;
    - Select the entire first column of NBA_skinny (the weight);
    - Get the height of Dennis Schroder;
    - Get the mean & median of the skinny players' weight (first column);

In [100]:
NBA_skinny = np.array([[74, 68, 77, 78, 79],
                    [183, 183, 190, 185,188]])
NBA_skinny.shape

(2, 5)

In [102]:
players = np.array([
    [74, 183],
    [68, 183],
    [77, 190],
    [78, 185],
    [79, 188]
])
players.shape

(5, 2)

In [104]:
NBA_skinny[0,:] #entire first column of NBA_skinny (the weight)

array([74, 68, 77, 78, 79])

In [106]:
players[:,0] #entire first column of NBA_skinny (the weight)

array([74, 68, 77, 78, 79])

In [108]:
NBA_skinny[1,3] # 4th elem 2nd row - height of Dennis Schroder

185

In [110]:
players[3,1] #  4th row, 2nd column - height of Dennis Schroder

185

In [112]:
# mean & median of the skinny players' weight (first column)
np.mean(players[:, 0])

75.2

In [114]:
np.mean(NBA_skinny[0, :])

75.2

In [116]:
np.median(players[:, 0])

77.0

In [118]:
np.median(NBA_skinny[0, :])

77.0

**Exercise 2**

You are going to work with data about the weight (in pounds) of the main basketball players in the NBA. These data are contained in the file *NBA_weight.csv*.

    - Import the data;
    - Create a NumPy array called 'NBA_lb' from the NBA players data you have just imported;
    - Create a NumPy array called 'NBA_kg' to get the weight in kilograms (1 kilogram =  2.2046 lbs);
    - Get an array with the heaviest basketball players, i.e. those whose weight is above 136 kg;
    - Obtain a sub-array of 'NBA_KG' that contains the elements at index 55 up to and including index 60.
    
To answer to the following two final questions, use the data in *NBA_info.csv*.

    - Compute the standard deviation of height;
    - Get the correlation between first and second column.

**Additional Exercise**

Write a function with the following specifications:
* It takes in two arguments: a string s (assume with just letters, no spaces or numbers) and a boolean upper_first. The default value for upper_first should be True.
* If upper_first is True, then the string characters of s should be rearranged such that uppercase letters come first. The order among uppercase characters should stay the same. The order among lower characters should stay the same.
* If upper_first is False, then the function behaves similarly, but with the lowercase characters first.

Example: fun("FrederikDeKeersmaeker", upper_first = True) outputs "FDKrederikeeersmaeker" and fun("anOVa", upper_first = False) outputs "rederikeeersmaekerFDK".

Hint: you will have to look up a function that checks whether or not a character is uppercase or lowercase.