# *pandas*

Python has been great for data munging and preparation, but less so for data analysis and modeling. Pandas helps fill this gap, enabling you to carry out your entire data analysis workflow in Python without having to switch to a more domain specific language like R.

The import convention for *pandas* is to import it as *pd*. So every time you encounter *pd* in the code, it is referring to *pandas*.

In [1]:
import pandas as pd

##  *pandas* Data Structures

In this section we will focus on two important data structures in *pandas*: **Series** and **DataFrame**.

### Series

A *Series* is a one-dimensional array-like object containing a sequence of values and an associated array of data labels, called its *index*. 

Another way to think about a *Series* is a fixed-length, ordered *dict*, as it is a mapping of index values to data values. It can be used in those situations where you can use a *dict*. You can create a *Series* from data contained in a *dict*.

In [3]:
prison_data = {'Belgium':11.071, 'France':71.190, 'Italy':54.653, 'Spain':61.526}

first_series = pd.Series(prison_data)
first_series

Belgium    11.071
France     71.190
Italy      54.653
Spain      61.526
dtype: float64

### DataFrame

A *DataFrame* contains an ordered collection of columns, each of which can be a different value type (numeric, string, boolean, ...). It has both a row and column index. Simply, if you paste together several *Series*, you obtain a *DataFrame*.

There are many ways to construct a *DataFrame*, such as starting from a *dict*.

In [5]:
country_dict = {
'country':['Belgium', 'France', 'Italy', 'Spain'],
'area':[30.689, 643.801, 301.338, 505.990],
'prison_pop':[11.071, 71.190, 54.653, 61.526],
'population':[11.31, 66.60, 60.67, 44.44]
}

first_df = pd.DataFrame(country_dict)
first_df

   country     area  prison_pop  population
0  Belgium   30.689      11.071       11.31
1   France  643.801      71.190       66.60
2    Italy  301.338      54.653       60.67
3    Spain  505.990      61.526       44.44

The data structure is clear: the rows represent the observations and the columns represent the variables. Each row has an automatically assigned label (from 0 to 3). If you want to set them manually, use the following syntax:

In [7]:
first_df.index = ["BE", "FR", "IT", "SP"]
first_df

    country     area  prison_pop  population
BE  Belgium   30.689      11.071       11.31
FR   France  643.801      71.190       66.60
IT    Italy  301.338      54.653       60.67
SP    Spain  505.990      61.526       44.44

Of course, you can import your dataset in Python by using several *pandas* import functions, which we saw how to do in Chapter 8.2.1. Here we want to import a new dataset, which comes from the USDA (United States Department of Agriculture) and it contains information about milk production in the USA.

In [9]:
import pandas as pd
filename = "C:\\Users\\Beryl\\Desktop\\Beryl\\KARU\\Units\\Karatina Uni\\SEM II\\STA 326\\Lecture Notes\\New Lecture notes\\Python Lecture notes\\FLAMES_Python_Part_3_2025\\state_milk_production.csv"
milk = pd.read_csv(filename)

In [11]:
milk.tail(20)
milk.head(20)

             region          state    year  milk_produced
0         Northeast          Maine  1970.0   6.190000e+08
1         Northeast  New Hampshire  1970.0   3.560000e+08
2         Northeast        Vermont  1970.0   1.970000e+09
3         Northeast  Massachusetts  1970.0   6.580000e+08
4         Northeast   Rhode Island  1970.0   7.500000e+07
5         Northeast    Connecticut  1970.0   6.610000e+08
6         Northeast       New York  1970.0   1.034100e+10
7         Northeast     New Jersey  1970.0   7.300000e+08
8         Northeast   Pennsylvania  1970.0   7.124000e+09
9         Northeast       Delaware  1970.0   1.300000e+08
10        Northeast       Maryland  1970.0   1.560000e+09
11      Lake States       Michigan  1970.0   4.602000e+09
12      Lake States      Wisconsin  1970.0   1.843500e+10
13      Lake States      Minnesota  1970.0   9.636000e+09
14        Corn Belt           Ohio  1970.0   4.420000e+09
15        Corn Belt        Indiana  1970.0   2.382000e+09
16        Corn Belt       Illinois  1970.0   2.850000e+09
17        Corn Belt           Iowa  1970.0   4.670000e+09
18        Corn Belt       Missouri  1970.0   3.012000e+09
19  Northern Plains   North Dakota  1970.0   1.065000e+09

You can use the info method to obtain information on a *DataFrame*.

In [13]:
milk.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2400 entries, 0 to 2399
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   region         2400 non-null   object
 1   state          2400 non-null   object
 2   year           2400 non-null   float64
 3   milk_produced  2400 non-null   float64
dtypes: float64(2), object(2)
memory usage: 75.1+ KB

You can use *dtypes* to see the data types for each variable

In [15]:
milk.dtypes

region            object
state             object
year             float64
milk_produced    float64
dtype: object

Get a list of all variables

In [17]:
milk.columns

Index(['region', 'state', 'year', 'milk_produced'], dtype='object')

There are multiple ways to index and select data from a *DataFrame*: using [ ] or using more advanced methods, such as *loc* and *iloc*.

To access only the "state" column, we can use its actual name, as shown here:

In [19]:
milk["state"].head(20)

0             Maine
1     New Hampshire
2           Vermont
3     Massachusetts
4      Rhode Island
5       Connecticut
6          New York
7        New Jersey
8      Pennsylvania
9          Delaware
10         Maryland
11         Michigan
12        Wisconsin
13        Minnesota
14             Ohio
15          Indiana
16         Illinois
17             Iowa
18         Missouri
19     North Dakota
Name: state, dtype: object

Note that the last line in the output tells us that the *dtype* is *object*. Which type of object is returned here? We can find out with the *type* function.

In [21]:
type(milk["state"])

pandas.core.series.Series

It turns out to be a *pandas Series*, i.e. a 1D labelled array (see previous section). A second way to extract one variable as a *pandas Series* is the following:

In [ ]:
milk.state

In [23]:
type(milk.state)

pandas.core.series.Series

To select the "state" column and to keep it in a *DataFrame* format, you need double squared brackets.

In [ ]:
milk[["state"]].head()

In [50]:
type(milk[["state"]])

pandas.core.frame.DataFrame

You can also access rows by using [ ]. If we want to access the rows between the second and the fifth, we use the following syntax:

In [27]:
milk[0:6]

      region          state    year  milk_produced
0  Northeast          Maine  1970.0   6.190000e+08
1  Northeast  New Hampshire  1970.0   3.560000e+08
2  Northeast        Vermont  1970.0   1.970000e+09
3  Northeast  Massachusetts  1970.0   6.580000e+08
4  Northeast   Rhode Island  1970.0   7.500000e+07
5  Northeast    Connecticut  1970.0   6.610000e+08

### Exercises: Working with *pandas DataFrame*

Look at the dataset called "pollution.xlsx". It contains information about weather and pollution in several US cities. 

    - Import the data, specifically the sheet called "usa_first_part";
    - By using the squared brackets, obtain a DataFrame with only 'City' and 'Rain' columns; 
    - By using the squared brackets, get the fifth, sixth, seventh observation; 
    - Use iloc to select the observation corresponding to Boston and Denver as DataFrame;
    - Create a DataFrame, containing the observations for Akron and Albany and the columns Education and HCPot;
    - Obtain NOxPot (Nitrous oxide pollution potential) column as a DataFrame. Make sure that you have the 
      correct type.
    - Extra part: if you have time, redo the exercise by setting "City" as the index and using the loc function.

## Manipulating DataFrames with *pandas*

### Filtering DataFrames

Filtering is useful when you wish to select part of the data based on specific properties. Behind filtering there is the idea of a Boolean *Series*.

In [29]:
milk.head()

      region          state    year  milk_produced
0  Northeast          Maine  1970.0   6.190000e+08
1  Northeast  New Hampshire  1970.0   3.560000e+08
2  Northeast        Vermont  1970.0   1.970000e+09
3  Northeast  Massachusetts  1970.0   6.580000e+08
4  Northeast   Rhode Island  1970.0   7.500000e+07

In [31]:
new_milk = milk[milk.milk_produced > 4.0000000e+10]
new_milk.head()

       region       state    year  milk_produced
1897  Pacific  California  2007.0   4.068300e+10
1947  Pacific  California  2008.0   4.120300e+10
2047  Pacific  California  2010.0   4.038500e+10
2097  Pacific  California  2011.0   4.146200e+10
2147  Pacific  California  2012.0   4.180100e+10

In [33]:
milk[milk.year == 2010].head()

         region          state    year  milk_produced
2000  Northeast          Maine  2010.0   5.870000e+08
2001  Northeast  New Hampshire  2010.0   2.940000e+08
2002  Northeast        Vermont  2010.0   2.521000e+09
2003  Northeast  Massachusetts  2010.0   2.420000e+08
2004  Northeast   Rhode Island  2010.0   2.000000e+07

Filters can be combined using the standard logical operators AND (& in Python) and OR (| in Python).

In [35]:
# using AND (&): both conditions have to be True
milk[(milk.milk_produced > 2.0000000e+10) & (milk.year == 2015)]

           region       state    year  milk_produced
2262  Lake States   Wisconsin  2015.0   2.903000e+10
2297      Pacific  California  2015.0   4.089700e+10

In [37]:
# using OR (|): at least one of the conditions has to be True
milk[(milk.milk_produced > 2.0000000e+10) | (milk.year == 2015)].tail(10)

           region       state    year  milk_produced
2294     Mountain      Nevada  2015.0   6.690000e+08
2295      Pacific  Washington  2015.0   6.606000e+09
2296      Pacific      Oregon  2015.0   2.551000e+09
2297      Pacific  California  2015.0   4.089700e+10
2298      Pacific      Alaska  2015.0   4.000000e+06
2299      Pacific      Hawaii  2015.0   3.500000e+07
2312  Lake States   Wisconsin  2016.0   3.011000e+10
2347      Pacific  California  2016.0   4.046900e+10
2362  Lake States   Wisconsin  2017.0   3.032000e+10
2397      Pacific  California  2017.0   3.979800e+10

You can filter a column based on another one. For example, you can select the years in which the quantity of milk produced is larger than 3.0000000e+10.

In [39]:
milk.year[milk.milk_produced > 3.0000000e+10]

1497    1999.0
1547    2000.0
1597    2001.0
1647    2002.0
1697    2003.0
1747    2004.0
1797    2005.0
1847    2006.0
1897    2007.0
1947    2008.0
1997    2009.0
2047    2010.0
2097    2011.0
2147    2012.0
2197    2013.0
2247    2014.0
2297    2015.0
2312    2016.0
2347    2016.0
2362    2017.0
2397    2017.0
Name: year, dtype: float64

**Dealing with NaNs**

Missing values are common in datasets. In Python, missing values are represented by **NaN** , which stands for 'not a number'. 

To show you how to deal with *NaN*, we add a new column about life expectancy that contains two missing values to our *country* dictionary. We need *NumPy* to add missing values.

In [41]:
import numpy as np
country_df = pd.DataFrame({
'country':['Belgium', 'France', 'Italy', 'Spain'],
'area':[30.689, 643.801, 301.338, 505.990],
'prison_pop':[11.071, 71.190, 54.653, 61.526],
'population':[11.31, 66.60, 60.67, 44.44],       
'life_exp': [80.99, np.nan, 82.54, np.nan]
})

country_df

   country     area  prison_pop  population  life_exp
0  Belgium   30.689      11.071       11.31     80.99
1   France  643.801      71.190       66.60       NaN
2    Italy  301.338      54.653       60.67     82.54
3    Spain  505.990      61.526       44.44       NaN

Given a DataFrame, how can we figure out which rows or which columns contain missing values? We can use the *isnull* method to indicate where entries are missing.

In [43]:
country_df.isnull()

   country   area  prison_pop  population  life_exp
0    False  False       False       False     False
1    False  False       False       False      True
2    False  False       False       False     False
3    False  False       False       False      True

The *any* method acts on columns or rows and returns True if and only if at least one of the entries is True. It acts on columns (axis = 0) by default, but acts on rows if you specify axis = 1.

In [45]:
country_df.isnull().any()

country       False
area          False
prison_pop    False
population    False
life_exp       True
dtype: bool

In [47]:
country_df.isnull().any(axis = 0)

country       False
area          False
prison_pop    False
population    False
life_exp       True
dtype: bool

In [49]:
country_df.isnull().any(axis = 1)

0    False
1     True
2    False
3     True
dtype: bool

The code below does the opposite, i.e. you only get the columns for which there are no missing data.

In [51]:
country_df.notnull().all()

country        True
area           True
prison_pop     True
population     True
life_exp      False
dtype: bool

If you are interested in the number of missing entries in each column, you can use the combination *isnull().sum()* and apply it to the entire DataFrame.

In [55]:
country_df.isnull().sum()

country       0
area          0
prison_pop    0
population    0
life_exp      2
dtype: int64

The methods *dropna* removes all rows with missing values. Proceeding with this data set leads to a **complete case analysis**.

In [57]:
country_df.dropna()

   country     area  prison_pop  population  life_exp
0  Belgium   30.689      11.071       11.31     80.99
2    Italy  301.338      54.653       60.67     82.54

**Transforming DataFrames**

We can transform our data using elementary arithmetic operations. For example, suppose we want to divide the prison population by 2 in our *country* DataFrame. We can use the *pandas* DataFrame vectorized method for floor division called *floordiv*. This arithmetic operation is applied to every entry in the DataFrame without using a loop.

In [59]:
country_df['prison_pop_divided'] = country_df.prison_pop.floordiv(2)  # save the values into a new variable
country_df

   country     area  prison_pop  population  life_exp  prison_pop_divided
0  Belgium   30.689      11.071       11.31     80.99                 5.0
1   France  643.801      71.190       66.60       NaN                35.0
2    Italy  301.338      54.653       60.67     82.54                27.0
3    Spain  505.990      61.526       44.44       NaN                30.0

As an alternative, you can use the *NumPy* vectorized function *np.floor_divide*.

In [94]:
import numpy as np
out = np.floor_divide(country_df.prison_pop, 2)  # NOT saving the results into a new variable
out

0     5.0
1    35.0
2    27.0
3    30.0
Name: prison_pop, dtype: float64

In [96]:
type(out)

pandas.core.series.Series

**Exercise**

Solve the following questions using the milk data set. Try to code as much as possible, i.e. try to print the result and only the result.

* In which US states has the annual milk production ever exceeded 20,000,000,000?
* For each of those states, figure out in which year the production first exceeded 20,000,000,000.

Hint: how do you get all **unique** values from a DataFrame columns or Series? How do you get the minimum? Experiment, or, even better, look it up online!

## Statistics with *pandas*

We can use *pandas* statistical functions to obtain summary statistics. Below we get an overview including standard statistics for all numerical variables.

In [61]:
import pandas as pd
filename = "C:\\Users\\Beryl\\Desktop\\Beryl\\KARU\\Units\\Karatina Uni\\SEM II\\STA 326\\Lecture Notes\\New Lecture notes\\Python Lecture notes\\FLAMES_Python_Part_3_2025\\tips.csv"
tips = pd.read_csv(filename)
tips.head(5)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [63]:
tips.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [65]:
tips["tip"].mean()  # automatically omits missing values

2.99827868852459

In [67]:
tips["tip"].std()

1.3836381890011826

In [69]:
tips["total_bill"].median()

17.795

In [73]:
tips.corr(numeric_only=True)

            total_bill       tip      size
total_bill    1.000000  0.675734  0.598315
tip           0.675734  1.000000  0.489299
size          0.598315  0.489299  1.000000

In [75]:
tips.corr(numeric_only=True, method = 'spearman')

            total_bill       tip      size
total_bill    1.000000  0.678968  0.604791
tip           0.678968  1.000000  0.468268
size          0.604791  0.468268  1.000000

In [77]:
tips.corr(numeric_only=True, method = 'kendall')

            total_bill       tip      size
total_bill    1.000000  0.517181  0.484342
tip           0.517181  1.000000  0.378185
size          0.484342  0.378185  1.000000

### 10.4 - Exercise: data manipulation with *pandas*

The US Social Security Administration has made available data on the frequency of baby names from 1880 to 2018. The name of this dataset is "names_data.csv". Import the data as a DataFrame and then:

* Find the top 10 most used male and female names;
* Find the top 20 gender neutral names (names that are used at least once for both male and female). Only take into account those names that at least have 50,000 records for each gender.